steps:
  - name: docker/compose
    volumes:
    - name: 'gradle'
      path: '/root/.gradle'
    args: ['run', '-v', '/workspace:/mnt', '-v', '/.gradle:/root/.gradle', '-w', '/mnt', '--rm', 'gradle', './gradlew', 'test', '--info']

timeout: 900s